"""stage2 regional excel models

Revision ID: 7d9601156933
Revises: 
Create Date: 2026-07-28 17:22:48.188802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9601156933'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('SZFO_1', 'SZFO_2', 'REGIONAL', 'MOSCOW', name='department'), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department', 'normalized_name', name='uq_manager_group_identity')
    )
    op.create_table('source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('SZFO_1', 'SZFO_2', 'REGIONAL', 'MOSCOW', name='department'), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('fingerprint_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'INVALID', name='source_file_status'), nullable=False),
    sa.Column('rejection_reasons', sa.JSON(), nullable=True),
    sa.Column('reported_grand_totals', sa.JSON(), nullable=True),
    sa.Column('reconciliation_report', sa.JSON(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', name='uq_source_file_sha256')
    )
    op.create_table('counterparties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_group_id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_group_id'], ['manager_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_group_id', 'normalized_name', name='uq_counterparty_identity')
    )
    op.create_table('debt_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('manager_group_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('parent_position_id', sa.Integer(), nullable=True),
    sa.Column('outline_level', sa.SmallInteger(), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('raw_label', sa.Text(), nullable=False),
    sa.Column('payment_deferral_days', sa.Integer(), nullable=True),
    sa.Column('payment_deferral_error', sa.Text(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('document_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('advance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('not_due', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('overdue_1_7', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('overdue_8_14', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('overdue_15_21', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('overdue_22_30', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('overdue_over_31', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('comment_raw', sa.Text(), nullable=True),
    sa.CheckConstraint('outline_level BETWEEN 1 AND 4', name='ck_debt_position_outline_level'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['manager_group_id'], ['manager_groups.id'], ),
    sa.ForeignKeyConstraint(['parent_position_id'], ['debt_positions.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debt_positions')
    op.drop_table('counterparties')
    op.drop_table('source_files')
    op.drop_table('manager_groups')
    # ### end Alembic commands ###

    # Autogenerate не удаляет ENUM-типы Postgres при drop_table — без явного
    # DROP TYPE повторный upgrade падает с "type already exists" (проверено
    # вручную циклом upgrade -> downgrade -> upgrade на локальном PostgreSQL).
    sa.Enum(name="department").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="source_file_status").drop(op.get_bind(), checkfirst=True)
